import { TFile, Vault } from "obsidian";
import type { CrmSettings } from "../settings";
import { normalizeFolderPath } from "../settings";
import { DEFAULT_STAGES, INTERACTION_KINDS } from "./integrity";
import { followUpTask } from "./next-action";
import { frontmatterList, normalizeStage } from "./pipeline";
import { companyNote, interactionNote, interactionTitle, opportunityNote, opportunityTitle, personNote } from "./templates";

// AGENTS.md (read by most coding agents) and CLAUDE.md (read by Claude Code)
// in the CRM root teach an AI agent to edit CRM notes directly without
// breaking the data contract. Examples come from the same templates the
// plugin uses, so the guide cannot drift from what the plugin writes.

export const AGENT_GUIDE_FILE = "AGENTS.md";
export const CLAUDE_FILE = "CLAUDE.md";
export const USER_NOTES_HEADING = "## Your notes";
export const USER_NOTES_MARKER = "<!-- Write your own instructions for agents below this line. They are kept when the guide is regenerated. -->";
export const CLAUDE_POINTER = "@AGENTS.md\n";

export interface AgentGuideOptions {
  root: string;
  stages: readonly string[];
  kinds: readonly string[];
  taskTag: string;
  createTasks: boolean;
}

export function renderAgentGuide(options: AgentGuideOptions): string {
  const { root } = options;
  const stages = options.stages.map(normalizeStage);
  const code = (items: readonly string[]) => items.map((item) => `\`${item}\``).join(", ");
  const task = options.createTasks ? followUpTask("Send proposal", "2026-10-12", options.taskTag) : "";

  const company = companyNote({ name: "Acme", site: "https://acme.example", industry: "Software" });
  const person = personNote({ name: "Jane Doe", company: "[[Acme]]", role: "Head of Operations", email: "jane@acme.example" });
  const deal = opportunityTitle("Acme", "Website redesign");
  const opportunity = opportunityNote({
    name: "Website redesign", companyLabel: "Acme", company: "[[Acme]]", contact: "[[Jane Doe]]",
    stage: stages[0] ?? "lead", value: "15000", created: "2026-10-05",
  });
  const callTitle = interactionTitle("2026-10-05", "call", "Jane Doe");
  const interaction = interactionNote({
    title: callTitle, date: "2026-10-05", kind: "call", people: ["[[Jane Doe]]"], company: "[[Acme]]",
    opportunity: `[[${deal}]]`, nextAction: "Send proposal", nextActionDate: "2026-10-12",
    summary: "Walked through the current site and the redesign scope.", task,
  });

  const taskRule = options.createTasks
    ? `When a next action is set, also add a Tasks-plugin line under \`## Next action\`, in exactly this format:\n\n\`${task}\``
    : "Follow-up tasks are disabled in the plugin settings: set `next_action` and `next_action_date` only, and do not add task lines.";

  return `# CRM — Agent Guide

> Generated by the Obsidian CRM plugin. Regenerate it with **CRM: Update agent guide** after changing pipeline stages or plugin settings. Only the "Your notes" section at the end is kept when the guide is regenerated.

\`${root}/\` is a CRM stored as plain Markdown in an Obsidian vault. Every company, person, opportunity and interaction is one note with YAML frontmatter. The CRM plugin reads these notes to show the pipeline and the contact lists. You may read, create and update them by editing files directly, as long as you follow this guide exactly: a note that breaks it breaks the pipeline, the lists, or the links between records.

## Rules you must always follow

1. **Search before you create.** Look for an existing record of the same type whose file name or \`name\` matches, ignoring case. If one exists, update it instead. If more than one matches, stop and ask the user which one they mean.
2. **Link both sides of every relationship.** A relationship is written in the frontmatter of one note and listed in the body of the other (see "Relationships"). A one-sided link is a bug.
3. **Never delete, rename or move a note** unless the user explicitly asks. Renaming breaks every \`[[link]]\` to the note. If a rename is needed, ask the user to do it in Obsidian, which updates the links.
4. **Never move \`last_contact\` backwards, and never clear a pending next action** with an empty one (see "Logging an interaction").
5. **Use only allowed values.** \`stage\` must be one of the pipeline stages and \`kind\` one of the interaction kinds (see "Reference"). Dates are always \`YYYY-MM-DD\`.
6. **Do not edit** \`Pipeline.md\`, \`Validation Report.md\`, \`${AGENT_GUIDE_FILE}\` or \`${CLAUDE_FILE}\` unless the user asks.
7. **Preserve what the user wrote.** Change only the fields and sections this guide describes; keep every other line as it is.
8. **Keep the data local.** These notes describe real people and companies. Do not send their content to external services or tools without the user's explicit consent.
9. **Write field names, headings and generated text in English.** Keep the user's own wording for names, notes and summaries.

## Folder layout

| Path | Contents | File name |
|------|----------|-----------|
| \`${root}/Companies/\` | \`crm/company\` notes | \`Name.md\` |
| \`${root}/People/\` | \`crm/person\` notes | \`Name.md\` |
| \`${root}/Opportunities/\` | \`crm/opportunity\` notes | \`Company - Name.md\` |
| \`${root}/Interactions/\` | \`crm/interaction\` notes | \`YYYY-MM-DD - kind - Person.md\` (the company when there is no person) |
| \`${root}/Pipeline.md\` | pipeline stages and board state | owned by the user |
| \`${root}/Validation Report.md\` | output of **CRM: Validate data** | generated |

In file names, replace each of \\ / : * ? " < > | # ^ [ ] with \`-\` and collapse repeated spaces. If the file name is already taken by a different record, append \` 2\`, \` 3\`, … before \`.md\`, and use that exact file name in every link.

## Note format

- **Links** are \`[[file name without .md]]\`, for example \`[[Acme]]\` or \`[[${deal}]]\`. In frontmatter, quote them: \`company: "[[Acme]]"\`. In body sections, list them one per line as \`- [[Acme]]\`, never twice in the same section.
- **Frontmatter values** are double-quoted strings. An empty value is the key with nothing after the colon (\`industry:\`); an empty list is \`[]\`.
- **\`crm_id\`** is \`<type>-<slug>\`, where the slug is the name in lowercase, with accents removed and every run of other characters replaced by \`-\`. Opportunities use \`Company-Name\` and interactions use the full title as the name. Set it once at creation and never change it.
- **Sections** are \`## Heading\`, then one blank line, the content, and one blank line before the next heading. Never put content directly against a heading.

## Relationships

Each relationship is stored on one side in frontmatter and listed on the other side in a body section:

| Relationship | Frontmatter field | Listed in |
|--------------|-------------------|-----------|
| A person works at a company | person \`company\` | company \`## People\` |
| An opportunity belongs to a company | opportunity \`company\` (also in its \`## Company\` section) | company \`## Opportunities\` |
| An opportunity has a contact | opportunity \`contact\` (also in its \`## Contact\` section) | person \`## Opportunities\` |
| An interaction involves people, a company and an opportunity | interaction \`people\`, \`company\`, \`opportunity\` | \`## History\` of each of those notes |

## Creating a company

Create \`${root}/Companies/Acme.md\`:

\`\`\`markdown
${company}\`\`\`

## Creating a person

Create \`${root}/People/Jane Doe.md\`. Leave \`company\` empty if you do not know it:

\`\`\`markdown
${person}\`\`\`

If the person works at a company, also add \`- [[Jane Doe]]\` under \`## People\` in the company note.

## Creating an opportunity

Create the company and the contact first if they do not exist. Then create \`${root}/Opportunities/${deal}.md\`. \`company\` is required, \`created\` is today's date, and \`value\` is a plain number without a currency symbol:

\`\`\`markdown
${opportunity}\`\`\`

Then:

- add \`- [[${deal}]]\` under \`## Opportunities\` in the company note and in the contact's note;
- if the contact's \`company\` is empty, set it to the opportunity's company and add the contact under the company's \`## People\`. If the contact already belongs to another company, leave it alone.

## Logging an interaction

Create the person and the company first if they do not exist. Then create \`${root}/Interactions/${callTitle}.md\`:

\`\`\`markdown
${interaction}\`\`\`

\`people\` is a list even with one person. ${taskRule}

Then update **each** related note (the person, the company and the opportunity):

- \`last_contact\`: the later of its current value and the interaction date. Never an earlier date.
- \`next_action\` and \`next_action_date\`: if the interaction has a next action, set them to it. If it has none, leave them unchanged.
- add \`- [[${callTitle}]]\` under \`## History\`.

## Updating records

- **Move an opportunity to another stage:** set \`stage\` to one of the allowed values, in lowercase. Change nothing else.
- **Set a next action on a note:** set \`next_action\` and \`next_action_date\`. ${options.createTasks ? "Add the task line under that note's `## Next action` section, creating the section at the end of the note if it is missing. Never add a second `## Next action` heading." : "Do not add task lines."}
- **Change an opportunity's company or contact:** update the frontmatter and the \`## Company\` / \`## Contact\` section, remove the opportunity's link from the old company's or contact's \`## Opportunities\`, and add it to the new one. The file name should then be \`NewCompany - Name\`: ask the user to rename it in Obsidian.
- **Edit a person or company:** change only the fields the user asked for.

## Reference

- **Pipeline stages** (from \`Pipeline.md\`; records store them in lowercase): ${code(stages)}.
- **Interaction kinds:** ${code(options.kinds)}.
- **Record types:** \`crm/company\`, \`crm/person\`, \`crm/opportunity\`, \`crm/interaction\`. \`tags\` always contains the record's own type.
- **Dates:** \`YYYY-MM-DD\` (\`date\`, \`created\`, \`last_contact\`, \`next_action_date\`).

## Before you finish

- [ ] Every new note is in the right folder, with the right file name, \`type\`, \`crm_id\` and \`tags\`.
- [ ] Every relationship appears on both sides, and no section lists the same link twice.
- [ ] No record was duplicated, deleted or renamed without the user asking.
- [ ] Ask the user to run **CRM: Validate data** and fix anything listed in \`${root}/Validation Report.md\`.

${USER_NOTES_HEADING}

${USER_NOTES_MARKER}
`;
}

// Keeps the user's text below the "Your notes" marker of the existing file.
export function mergeUserNotes(generated: string, existing: string): string {
  const heading = existing.indexOf(`\n${USER_NOTES_HEADING}\n`);
  if (heading === -1) {
    return generated;
  }
  let notes = existing.slice(heading + USER_NOTES_HEADING.length + 2);
  const marker = notes.indexOf(USER_NOTES_MARKER);
  if (marker !== -1) {
    notes = notes.slice(marker + USER_NOTES_MARKER.length);
  }
  notes = notes.trim();
  return notes ? `${generated.trimEnd()}\n\n${notes}\n` : generated;
}

export async function ensureAgentGuide(vault: Vault, settings: CrmSettings): Promise<void> {
  await writeAgentGuide(vault, settings, false);
}

export async function updateAgentGuide(vault: Vault, settings: CrmSettings): Promise<void> {
  await writeAgentGuide(vault, settings, true);
}

async function writeAgentGuide(vault: Vault, settings: CrmSettings, overwrite: boolean): Promise<void> {
  const root = normalizeFolderPath(settings.crmRoot);
  const guidePath = `${root}/${AGENT_GUIDE_FILE}`;
  const claudePath = `${root}/${CLAUDE_FILE}`;
  const existingGuide = vault.getAbstractFileByPath(guidePath);

  if (!existingGuide || overwrite) {
    const generated = renderAgentGuide({
      root,
      stages: await pipelineStages(vault, root),
      kinds: INTERACTION_KINDS,
      taskTag: settings.taskTag,
      createTasks: settings.createTasksByDefault,
    });
    if (existingGuide instanceof TFile) {
      await vault.process(existingGuide, (current) => mergeUserNotes(generated, current));
    } else {
      await vault.create(guidePath, generated);
    }
  }

  if (!vault.getAbstractFileByPath(claudePath)) {
    await vault.create(claudePath, CLAUDE_POINTER);
  }
}

async function pipelineStages(vault: Vault, root: string): Promise<string[]> {
  const file = vault.getAbstractFileByPath(`${root}/Pipeline.md`);
  if (file instanceof TFile) {
    const stages = frontmatterList(await vault.read(file), "stages");
    if (stages?.length) {
      return stages;
    }
  }
  return [...DEFAULT_STAGES];
}
